### ISSUE TITLE
Updates on torchscript for iOS?

### ISSUE THREAD

**Issue by Gaozhongpai** [dsuess/mediapipe-addons#1]
Hi @dsuess, would you continue to work on this for mobile iOS? Thanks

**Comment by dsuess** [comment]
Thanks for your interest @Gaozhongpai. I've originally tried to get it working on mobile. Back then, there was no GPU support, so I didn't pursue. It's also much more challenging because back then, pytorch mobile didn't support the bazel build system, so  you'd have to wrap the existing cmake build system
